
services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main-network
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - mariadb
      - redis
    restart: always
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - wordpress
    restart: always
  
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - main-network
    restart: always

networks:
  main-network:
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/achakkaf/data/website
      o: bind
      type: none
  db-data:
    driver: local
    driver_opts:
      device: /home/achakkaf/data/database
      o: bind
      type: none
  redis-data:
    driver: local
    driver_opts:
      device: /home/achakkaf/data/redis
      o: bind
      type: none
