version: '3.5'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/achakkaf/Documents/mount/wordpress
      o: bind
      type: none 

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
        device: /home/achakkaf/Documents/mount/mariadb
        o: bind
        type: none

networks:
  main:
      name: main

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - main
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    networks:
      - main
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    restart: always
    
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    networks:
      - main
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: always

