# version: '3.9'

# services:
#   nginx:
#     build: ./requirements/nginx
#     ports:
#       - "8080:80"
#     depends_on:
#       - wordpress
#     networks:
#       - test
#     volumes:
#       - ./requirements/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

#   mariadb:
#     build: ./requirements/mariadb
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress_user
#       MYSQL_PASSWORD: wordpress_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - test

#   wordpress:
#     build: ./requirements/wordpress
#     environment:
#       WORDPRESS_DB_HOST: mariadb:3306
#       WORDPRESS_DB_NAME: wordpress
#       WORDPRESS_DB_USER: wordpress_user
#       WORDPRESS_DB_PASSWORD: wordpress_password
#     ports:
#       - "9000:80"
#     depends_on:
#       - mariadb
#     networks:
#       - test
#     restart: alwauys 

# networks:
#   test:
#     driver: bridge

# volumes:
#   mariadb_data:

