
services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main-network
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    restart: always
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - wordpress
    restart: always

networks:
  main-network:
    name: main-network
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/achakkaf/mount/website
      o: bind
      type: none
  db-data:
    driver: local
    driver_opts:
      device: /home/achakkaf/mount/database
      o: bind
      type: none