
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main-network
    env_file:
      - .env
    restart: always

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      - main-network
    restart: always
  
  vsftpd:
    build: ./requirements/bonus/FTP
    image: vsftpd
    container_name: vsftpd
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - main-network
    env_file: 
      - .env
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks:
      - main-network
    ports:
      - "8080:8080"
    restart: always

  grafana:
    build: ./requirements/bonus/grafana
    image: grafana
    container_name: grafana
    networks:
      - main-network
    ports:
      - "3000:3000"
    restart: always

  website:
    build: ./requirements/bonus/website
    image: website
    container_name: website
    ports:
      - "80:80"
    restart: always

networks:
  main-network:
    driver: bridge

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      device: /home/achakkaf/data/wordpress
      o: bind
      type: none

  db-data:
    name: db-data
    driver: local
    driver_opts:
      device: /home/achakkaf/data/database
      o: bind
      type: none
